// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCraUQL3WOGhaXKAGK8gZFJp2pWaTfBYRk',
    appId: '1:599848128669:web:9de24e3a8f21138d3b8474',
    messagingSenderId: '599848128669',
    projectId: 'pushnotiproject-a21ed',
    authDomain: 'pushnotiproject-a21ed.firebaseapp.com',
    storageBucket: 'pushnotiproject-a21ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9qkWyw5EpRuHUIpD-eCHNXugZ_7WN69E',
    appId: '1:599848128669:android:bba0f2c91e855e4b3b8474',
    messagingSenderId: '599848128669',
    projectId: 'pushnotiproject-a21ed',
    storageBucket: 'pushnotiproject-a21ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxly-gkLxlm-x_-jPXG9mzsKnHi5m3EUg',
    appId: '1:599848128669:ios:54b018e6a5bd3f053b8474',
    messagingSenderId: '599848128669',
    projectId: 'pushnotiproject-a21ed',
    storageBucket: 'pushnotiproject-a21ed.firebasestorage.app',
    iosBundleId: 'com.example.dzhegloFlutterPushNotifications',
  );
}
